var tree = [["Icecave",,"",
                [["Parity","Icecave\/Parity.html","",
                [["Comparator","Icecave\/Parity\/Comparator.html","",
                [["ComparatorInterface","Icecave\/Parity\/Comparator\/ComparatorInterface.html","",
                [        ]],["DeepComparator","Icecave\/Parity\/Comparator\/DeepComparator.html","",
                [        ]],["ParityComparator","Icecave\/Parity\/Comparator\/ParityComparator.html","",
                [        ]],["PhpComparator","Icecave\/Parity\/Comparator\/PhpComparator.html","",
                [        ]],["StrictPhpComparator","Icecave\/Parity\/Comparator\/StrictPhpComparator.html","",
                [        ]]        ]],["Exception","Icecave\/Parity\/Exception.html","",
                [["NotComparableException","Icecave\/Parity\/Exception\/NotComparableException.html"," < LogicException",
                [        ]]        ]],["AbstractExtendedComparable","Icecave\/Parity\/AbstractExtendedComparable.html","",
                [        ]],["AnyComparableInterface","Icecave\/Parity\/AnyComparableInterface.html","",
                [        ]],["ExtendedComparableInterface","Icecave\/Parity\/ExtendedComparableInterface.html","",
                [        ]],["PackageInfo","Icecave\/Parity\/PackageInfo.html","",
                [        ]],["Parity","Icecave\/Parity\/Parity.html","",
                [        ]],["RestrictedComparableInterface","Icecave\/Parity\/RestrictedComparableInterface.html","",
                [        ]],["SelfComparableInterface","Icecave\/Parity\/SelfComparableInterface.html","",
                [        ]]        ]]        ]]        ]

